### ISSUE TITLE
v4.1.0 Agenda has no construct signatures

### ISSUE THREAD

**Issue by houxinli** [agenda/agenda#1265]
agenda: v4.1.0

error TS2351: This expression is not constructable.

Type 'typeof import("path_to/node_modules/agenda/dist/index")' has no construct signatures.

code
```ts
import Agenda from "agenda";

const agenda = new Agenda(connection_options);

**Comment by houxinli** [comment]
`export default Agenda` is missing in `dist/index.d.ts`
I tried manually adding this line in node_modules and it's working.

**Comment by houxinli** [comment]
currently using `@ts-expect-error` for build

**Comment by RA80533** [comment]
There's definitely a discrepency between the type declaration files available:

- **dist/index.d.ts** from adc22b8

    ```ts
    export * from "./agenda";
    export * from "./job";
    export { DefineOptions, JobPriority, Processor } from "./agenda/define";
    export { JobOptions } from "./job/repeat-every";
    import { Agenda } from "./agenda";
    export default Agenda;
    //# sourceMappingURL=index.d.ts.map
    ```

- **dist/index.d.ts** from [`agenda@4.1.0`](https://www.npmjs.com/package/agenda/v/4.1.0)

    ```ts
    export { Agenda, AgendaConfig } from "./agenda";
    export { DefineOptions, JobPriority, Processor } from "./agenda/define";
    export { JobOptions } from "./job/repeat-every";
    //# sourceMappingURL=index.d.ts.map
    ```

In the meantime, @houxinli, use a named import like so:

```ts
import { Agenda } from "agenda";
```

**Comment by houxinli** [comment]
> There's definitely a discrepency between the type declaration files available:
> 
> * **dist/index.d.ts** from [adc22b8](https://github.com/agenda/agenda/commit/adc22b8b662e6e59364cf6bb4f2518e00606e482)
>   ```ts
>   export * from "./agenda";
>   export * from "./job";
>   export { DefineOptions, JobPriority, Processor } from "./agenda/define";
>   export { JobOptions } from "./job/repeat-every";
>   import { Agenda } from "./agenda";
>   export default Agenda;
>   //# sourceMappingURL=index.d.ts.map
>   ```
> * **dist/index.d.ts** from [`agenda@4.1.0`](https://www.npmjs.com/package/agenda/v/4.1.0)
>   ```ts
>   export { Agenda, AgendaConfig } from "./agenda";
>   export { DefineOptions, JobPriority, Processor } from "./agenda/define";
>   export { JobOptions } from "./job/repeat-every";
>   //# sourceMappingURL=index.d.ts.map
>   ```
> 
> In the meantime, @houxinli, use a named import like so:
> 
> ```ts
> import { Agenda } from "agenda";
> ```

it would be right at compile but will cause runtime error ( sth like agenda_1.Agenda is not a construction function)

**Comment by houxinli** [comment]
Plus, the AgendaConfig type definition has some problem. In my use case I'm using a mongoDB instanse and the collection property in the db option (not using address and other MongoClientOptions)
```ts
interface AgendaConfig{
    ...
    mongo?: MongoDb;
    db?: {
        address: string;
        collection: string;
        options: MongoClientOptions;
    };
```

**Comment by BonnieMilian** [comment]
adding `export default Agenda` in index.d.ts worked for me too.
Please release soon the fix.

meanwhile with this works:
```
import Agenda from 'agenda'
new Agenda()
```

**Comment by RA80533** [comment]
This was fixed in #1268 although it appears that there hasn't been a new release to npm since then. In the meantime, you can install the package directly from the repository via `npm install git://github.com/agenda/agenda.git`.

Check out the documentation on [`npm-install`](https://docs.npmjs.com/cli/v7/commands/npm-install) for more information on installing non-npm packages.

**Comment by BonnieMilian** [comment]
Thanks @RA80533 and the @types/agenda from where should be installed?

in typescript is throwing:
`Cannot find module 'agenda' or its corresponding type declarations`
I installed "@types/agenda": "^4.1.0" as dev
and "agenda": "git://github.com/agenda/agenda.git"

**Comment by BonnieMilian** [comment]
Thanks @RA80533 

in typescript is throwing:
Cannot find module 'agenda' or its corresponding type declarations
and "agenda": "git://github.com/agenda/agenda.git"

**Comment by RA80533** [comment]
Did you per chance receive an error when you tried to install the package? I'm getting a checksum mismatch for jsdoc-template:

https://github.com/agenda/agenda/blob/7795fb4258d76c3b6c5a2912c2ac9e1f7af9a417/package.json#L71

**Comment by koresar** [comment]
@simison do you know much about jsdoc-template thing?

**Comment by RA80533** [comment]
It appears that jsdoc-template was never published to npm by Braintree (the owner of the repository). Its README instructs the developer to clone the project in order to use it.

Since Agenda is now written in TypeScript, it might make more sense to use TypeScript-oriented tooling to generate documentation (e.g., [TSDoc](https://github.com/microsoft/tsdoc)), especially so since much of the original JSDoc has been rewritten as TypeScript annotations.

**Comment by koresar** [comment]
@RA80533 you sound much experience, very knowledgeable.
Would you help us improving the docs please?

**Comment by simison** [comment]
@koresar I don't know but let's ask @simllll  👋

**Comment by koresar** [comment]
Agenda 4.1.2 was just released. It has these exports: https://unpkg.com/browse/agenda@4.1.2/dist/index.d.ts
Should be good enough for the initial bug reports.

Regarding docs - maybe we should move the discussion to here?  https://github.com/agenda/agenda/pull/1201

**Comment by RA80533** [comment]
Thanks, @koresar. I'll take a look.

**Comment by erenertas** [comment]
With these:

- "agenda": "^5.0.0", (version)
- In tsconfig.json, "module" = "NodeNext"
- In package.json,   "type": "module"

it is usable with `@ts-expect-error`

BUT, IntelliSense in VSCode is not working. 

Since IntelliSense doesn't work, I can't use the interfaces I created with agenda.define with agenda.schedule later. So I'm creating workarounds. 

I have `export default Agenda;` in `dist/index.d.ts` but I still get this issue
