### ISSUE TITLE
job.run() is not locking the job when running

### ISSUE THREAD

**Issue by yupadhya** [agenda/agenda#178]
when starting a job with job.run() , the job is not getting locked when running.
Following is the code.

``` javascript

   var job=agenda.create('myjob',{"name":"yogesh"});
   job.attrs.nextRunAt=null;
   job.save(function(err){
    job.run(function(err,job){
        console.log("Job completed")
        console.log(JSON.stringify(job));     //print job 1
        if(err)
        console.log(err);
     });
   });

  agenda.define('myjob', {lockLifetime:10000} , function(job, done) {
      console.log(JSON.stringify(job));       //Print job 2
     setTimeout(function(){
         done();
     },10000);
  });

  setTimeout(function(){
      job.run(function(err,job){
           console.log("second run of Job completed")
          console.log(JSON.stringify(job));      // print job 3
      })
  },5000)

 agenda.start();
```

Here  the second  run will start while the previous run is going on.
and the print statement 2 in define() will print

```
{"name":"myjob","data":{"name":"yogesh"},"type":"normal","priority":0,"nextRunAt":null,"_id":"55829bfffc6d7d6f02923527","lastRunAt":"2015-06-18T10:22:55.218Z"}
```

which has no property as "lockedAt" at all.
but the print statement 1 and 3 , that are executing after the completion of the run are showing "lockedAt" property.

```
{"name":"myjob","data":{"name":"yogesh"},"type":"normal","priority":0,"nextRunAt":null,"_id":"55829bfffc6d7d6f02923527","lastRunAt":"2015-06-18T10:23:00.190Z","lastFinishedAt":"2015-06-18T10:23:05.221Z","lockedAt":null}
```

**Comment by hughmp** [comment]
I'm getting the same problem. Is this intentional behavior?

What's the best way to lock a job when running it manually outside its usual schedule?

**Comment by lushc** [comment]
Yes, this is intentional because the mechanism for locking & queuing jobs is separate. If you've created a job that repeats at a regular interval, e.g. `agenda.every('4 hours', 'email stuff')`,  but want to run it now you can just do:

```js
job.schedule(new Date());
job.save(); // async
```


and the job will be locked & executed immediately. Something to bear in mind is that the next run at time is calculated from the last run at time, so in my example if this "every 4 hour" job was due to run in 30 minutes (which coincidentally lines up to be at 5pm) but you execute it now, then it'll be scheduled to next run at 8:30pm rather than 9pm. This isn't a problem because the job will still repeat at the right interval, but if you're relying on the job to run at a certain time then [repeatAt](https://github.com/agenda/agenda#repeatattime) should be used instead.

**Comment by hughmp** [comment]
Thanks @lushc !

I'm using the equivalent of this to begin with:
```js
job.repeatEvery('0 6 * * *', {
  timezone: 'America/New_York'
});
job.save();
```

Then at any point during run time someone can call an api which runs:
```js
job.schedule(new Date());
job.save();
```
to run the job immediately.

I want to keep the original cron schedule of `0 6 * * *` active. Should I be calling `job.repeatEvery()` and `job.save()` again to prevent any undesired offset?
