### ISSUE TITLE
High ram usage on queries causes crashes

### ISSUE THREAD

**Issue by KfirShainholtz** [agenda/agenda#411]
Hello everybody,
I've been using agenda for a while now,
and I have a bit of a problem lately,

I'm running 400-600 recurrent jobs, that each run one to six-seven queries.
The queries could have up to 8000 results, that each of them could contain a quite big json object.

My question is, can I somehow make sure that the server won't crash when agenda is running
the queries? something like streaming for the results, but out of the box, for me?

I purge all my jobs at startup, and load them again, the timing for each job is a bit different,
but sometimes 10-30 jobs could run together.

Maybe PM2 could be helpful? sharding?
Thank you very much!

**Comment by gastonelhordoy** [comment]
Hey @KfirShainholtz , I'm not completely sure if your problem is with Agenda's queries or with your concurrent jobs retrieving lot of information all together.

I guess it's the latter, so quick question, do you really need to retrieve all the information at once? Maybe something like [mongoose cursors](http://thecodebarbarian.com/cursors-in-mongoose-45) can help you out decreasing the memory required by the app.

**Comment by KfirShainholtz** [comment]
I do need to retrieve all the information at once, because the logics 
of aggregating the queries (injecting the results to the next query) is
used in the server, and then being sent to the query-run servers.

I guess I may need to cluster everything, but how could I load-balance everything,
when Agenda is not a stateless package?

**Comment by simison** [comment]
Please also ensure that you have all the required indices built.

Closing as a bit old support request at this point — feel free to re-open!
