### ISSUE TITLE
Lose scope within callback-function

### ISSUE THREAD

**Issue by renehauck** [agenda/agenda#432]
Hi,

if I define outside of the callback function a variable, it is undefined within the function. 

Can I bind "this" to agenda?

My code:

```js
var Agenda = require("agenda");
var OfferManager;
var TaskRunner = (function () {
    function TaskRunner(mongoUrl, offermanager) {
        var _this = this;
        this.offermanager = offermanager;
        OfferManager = offermanager; //<---------OfferManager is defined
        this.agenda = new Agenda(...);
        this.agenda.define('removerOffer', { priority: 'high', concurrency: 10 }, function (job, done) {
            var data = job.attrs.data;
            OfferManager.remove(data.articleId, done); //<------Error: OfferManager is undefined
        });
        this.agenda.on('ready', function () {
            _this.agenda.start();
        });
    }
...
```
Thx

**Comment by menzow** [comment]
Hey @renehauck,

Why do you define `OfferManager` outside of the scope of `TaskRunner`? And why do you define TaskRunner as an iife?

There's no way to know that `OfferManager` has not been reset to `undefined` when your task runs. I'd recommend using `_this.offermanager.remove` instead of `OfferManager.remove`. That way you're not depending on the global scope.

PS: I know this is an old question, but I'm just answering it so @OmgImAlexis can close it. Might it not be a good idea to refer questions such as these to Stackoverflow? It's not directly related to the package but does fill up the open issues.

**Comment by renehauck** [comment]
ok, thx
