### ISSUE TITLE
repeatEvery job using cron time will run job immediately

### ISSUE THREAD

**Issue by xurt75** [agenda/agenda#457]
I have tried a cron type job using the job.repeatEvery(). Whatever I set the cron-time, the job will start immediately once, and then nextRunAt the correct cron schedule time. It is confuse to me. 

I have added line 128 this.computNextRunAt() in repeatEvery() function in lib/job.js as follows. Then it works ok! I am not sure about this. Could you give some comments on this issue?
```
124 Job.prototype.repeatEvery = function(interval, options) {
125   options = options || {};
126   this.attrs.repeatInterval = interval;
127   this.attrs.repeatTimezone = options.timezone ? options.timezone : null;
128   this.computeNextRunAt();
129   return this;
130 };
```

**Comment by simison** [comment]
Similar / duplicate: #422 _Scheduling job with agenda.every method with human interval runs the job immediately_

**Comment by nemozny** [comment]
Yes, this one is a real pain!

I found a workaround though (and sorry, I can't get new lines in code working):
TESTjob.repeatEvery("1 2 * * *", {timezone: 'America/Chicago'});   
TESTjob.fail("Workaround to have a timestamp");
TESTjob.save();

**and then**

agenda.define('TESTjob', function(job, done) {
   if (new Date() - job.attrs.failedAt < 60000) {
   console.log("Only less than 1 minute (" +Math.floor((new Date() - job.attrs.failedAt) / 1000)+ "s) since the first run, so exit now");
   return done();
}
}

Please indent at your convenience.

**This way if Agenda tries to execute the job immediately, you calculate the duration since the job.fail timestamp (job.attrs.failedAt(date) - in miliseconds, so 1 minute is 60 seconds * 1000 ms) and break the execution with done().
In case you have doubts about this breaking the real job.fail, then you can check against job.attrs.failReason(string) too.**

**Comment by simison** [comment]
@nemozny would this work:
```js
const interval = '30 minutes';
const job = agenda
  .create('myJob')
  .schedule(`in ${interval}`)
  .repeatEvery(interval);
```
via https://github.com/Codevate/agenda/commit/7f0667d2a2120c8a4566e2d086d325e446e86ce8#commitcomment-22911598 by @lushc

**Comment by nemozny** [comment]
@simison No, this gets also executed immediately. Although I used this code, but I see no difference here, except maybe "in interval", which I cannot use:

const interval = '1 2 * * *';  
const job = agenda  
  .create('myJob')  
  .schedule(interval)  
  .repeatEvery(interval)
.save();

**Comment by simison** [comment]
In Agenda v2.0.0 `repeatEvery()` has `skipImmediate` option that should fix this. See the docs for details.
