### ISSUE TITLE
question: every() same job with different data

### ISSUE THREAD

**Issue by leabdalla** [agenda/agenda#50]
I'm trying to run same job with different params.

```
_agenda.every('15,35,55 * * * *',   'myjob', {name:"john"});
_agenda.every('40 minutes',         'myjob', {name:"mark"});
_agenda.every('0 17,13,19 * * *',   'myjob', {name:"bill"});
_agenda.every('0 2,14 * * *',       'myjob', {name:"steve"});
```

I know every() saves only one doc in database. but why?

Is there any way to do what i'm trying without re-define same job function many times?

**Comment by dandv** [comment]
@rschmukler 

> Every is a bit of a shorthand

This should be documented, because it's tripped enough people that there are two bugs against this behavior, and who knows how many others have run into it but found one of them. It's a common use case to have something like,

```js
agenda.define('send update email', (job, done) => { ... });
agenda.every('1 day', 'send update email', { users: usersSubcribedToDailyEmails, body: dailyUpdate });
agenda.every('1 week', 'send update email', { users: usersSubcribedToWeeklyEmails, body: weeklyUpdate });
```

> You will only want to run that once

What is the recommended way to run a set of `agenda.create(...).repeatEvery(...).save()` calls only once from, say, a script that creates these `send update email` jobs? It would be really useful to add this example to the [Sample project structure](https://github.com/agenda/agenda#example-project-structure), which right now doesn't illustrate job scheduling at all - it only calls `agenda.now()` once.
