### ISSUE TITLE
Starting jobs at restart of node server

### ISSUE THREAD

**Issue by nicolocarpignoli** [agenda/agenda#504]
I have probably a trivial question. I correctly schedule dynamic jobs:

```
   var agenda = new Agenda({ mongo: Mongo.getMongoConnection() });
    agenda.define(jobName, function (job, done) {
        job.alert = alert;
        func(job, done);
    });
    agenda.on("ready", function () {
        agenda.schedule(formatDate(date), jobName, data);
        agenda.start();
    })
```

This works if I keep my node server running. If i restart It, no job is scheduled (outdated jobs and jobs with future nextRun time). At server startup I do:

```
var agenda = new Agenda({ mongo: Mongo.getMongoConnection() });
    agenda.on("ready", function () {
        agenda.start();
        console.log("Starting agenda scheduler...");
    })
```

I also attach a 'find' query result of one of the jobs:

```{
    "_id" : ObjectId("598f9f957390ae1e79b3ec89"),
    "data" : {
        "hasToBeRemoved" : false
    },
    "lastModifiedBy" : null,
    "name" : "Power",
    "nextRunAt" : ISODate("2017-08-13T02:45:00.472+02:00"),
    "priority" : 0,
    "repeatInterval" : "*/15 * * * *",
    "repeatTimezone" : null,
    "type" : "single"
}
```
Can you help me find the problem?

**Comment by michelem09** [comment]
Please have a look at this https://github.com/agenda/agenda/issues/410

**Comment by nicolocarpignoli** [comment]
Already seen, but the suggested workarounds such as  https://github.com/agenda/agenda/issues/410#issuecomment-310526028 doesn't work because my job on mongodb (as you can see on my previous post) haven't got fields like `lockedAt` or `lastFinishedAt`

**Comment by bastianwegge** [comment]
@nicolocarpignoli we got it working using the latest version of `agenda`. Which version are you using?

**Comment by nicolocarpignoli** [comment]
@bastianwegge I'm using agenda@0.9.1; actually I ended up with reading data about jobs from mongo and manually reschedule every job, but it's clear that this is the standard behaviour that I was expected from the library

**Comment by bastianwegge** [comment]
I think there should be some kind of "dev" mode that closes jobs after they're done. Please have a look at the comment I wrote here: https://github.com/agenda/agenda/issues/410#issuecomment-324516380

And btw. agenda@1.0.0 was just released and seems to be working nicely.

**Comment by timqian** [comment]
<img width="685" alt="screen shot 2018-03-19 at 4 22 47 pm" src="https://user-images.githubusercontent.com/5512552/37584789-d751c04c-2b91-11e8-963c-9f7ed2a6f180.png">
@nicolocarpignoli Met similar issue today. The issue is when the server restart, the jobs need to be redefined, cause agenda did not save job function in database.

In your case, the job `Power` need to be defined when server start again.
```
    agenda.define('Power', function (job, done) {
        job.alert = alert;
        func(job, done);
    });
```
## Ref:
- [Agenda needs definitions in order to search for the jobs later. As such, you shouldn't be dynamically defining your jobs.](https://github.com/agenda/agenda/issues/109#issuecomment-60286993)
- [dynamicly add `every` type of job](https://github.com/agenda/agenda/issues/410#issuecomment-310542045)

**Comment by nicolocarpignoli** [comment]
`because agenda did not save job function in database.`
this is disappointing in my opinion. It will be a very useful functionality to add.

thanks anyway for the help :)
