### ISSUE TITLE
Question: how to finish a async job via http quest?

### ISSUE THREAD

**Issue by treecy** [agenda/agenda#556]
**My situation :**
My job sends a request to another server, and it could cost more than 30 minutes to finish this job.
I don't want to keep the socket waiting.
So I'm trying to make the other server send a http request to agenda sever, after the job is finished.

**The problem is:**
I didn't find a way to call the `done()` function(finish this job) out of `definition` function.

The done function looks quite simple, just resets `lastFinishedAt` and `lockedAt`, and emits some event.
I can extend a `done` method to `Job` property manually , but I want to know if there is a native way for my case?

Thank you!

**Comment by simison** [comment]
Hey!

It sounds like you should treat Agenda job as an _initiator_ for that long polling process. You could then store the state of your task either in a form of another Agenda job or in separate a storage.

Then either just keep polling the other server or have an listening endpoint, and once the server 2 signals it's done run the 2nd "finish" job.

So something like this:

1. Define jobs A and B by some mutual ID
1. Agenda Job A on server 1 initiates the process at server 2 => `done()`
1. Server 2 signals to an endpoint at server 1 (or you could have recurring Agenda job polling the server 2)
1. Agenda Job B on server 1 finishes up the process => `done()`

You'll probably just want to define both jobs first and then call `[.now()`](https://github.com/agenda/agenda#nowname-data-cb) when needed.

You might need to build something so that things keep rolling even if servers are down.

Hope this helps!
