### ISSUE TITLE
Question:  server restarted, some scheduled jobs are now listed as queued with next run in the past .

### ISSUE THREAD

**Issue by waxmenow** [agenda/agenda#560]
These jobs never ran.  server was running when I would have expected them to have run.  

Now they are listed as queued in the past.  I ran agenda.start() at the beginning of my code.

here is more or less what i am running. 

```javascript
   agenda.define(agendaName, {
        priority: 'high',
        concurrency: 10
    }, function (job, done) {


        stripe.charges.capture(req.session.stripeChargeId, function (err, charge) {
            // asynchronously called

            if (err !== 'undefined' && err) {
                console.log("error = " + err)
                notification_utilities.notifySlack("server_messages", "attempt to schedule a capture failed with message:" + err);
            } else {
               
            }
        })
        done();
    });

    agenda.schedule(scheduleTime, agendaName, {
    });
```

Can someone answer a few questions?

What does status queued mean... as distinct from scheduled?

and do I need to run some code on restart?  I'm still getting the agenda lingo so might be missing some obvs things.

Thank you!

B

**Comment by Mr-Sharma** [comment]
I have the same problem. Please let me know if you find the solution.

**Comment by Mr-Sharma** [comment]
Hi @waxmenow , 

My issue got resolved by running worker.js file separately as mentioned in the docs.
My jobs used to get queued when their trigger(next run time) is up and the server is not running at that particular time or if the server is restarted. 
The jobs get completed from "scheduled" state if the worker.js file is running even if the server is not running.
In my case I used to trigger jobs using HTTP request. I hope the jobs get into "queued" state because when the "next run time" is up, there will be no instance of agenda running as the server got restarted.

Please let me know if you find a better solution.
Thank You

**Comment by waxmenow** [comment]
Mr-Sharma:  can you post your worker.js?  or generic parts of it?  had a little trouble following your fix!
"the server is not running" - which server?

**Comment by simison** [comment]
Feel free to reopen for further discussion.
