### ISSUE TITLE
Org cleanup — heads up!

### ISSUE THREAD

**Issue by simison** [agenda/agenda#570]
Hello @dylanjha @ebourmalo @gastonelhordoy @jpiepkow @loris @michelem09 _aaand_ @droppedoncaprica 

You're getting pinged because in the past you've offered some help for the awesome job scheduling lib Agenda.js 🎉 

Would you have time to help us out in coming months? There's a ton to do! If you're busy, that's okay too. We'll remove inactive from our org list. We can add you back again if you step up to help someday!

We're now ES6, the code is much more modular than it used to be and tests run in Ava (kudos to @OmgImAlexis). We also have a Slack channel, [join us there!](https://slackin-ekwifvcwbr.now.sh/)

A good place to start is to do some triaging:
https://github.com/agenda/agenda/issues
https://github.com/agenda/agenda/pulls

Making nice documentation site for Agenda would an easy way to get started, too. :-)

Check also Agendash:
https://github.com/agenda/agendash

We also have some race condition happening with our tests and they tend to fail kinda randomly. Any idea why?

Aight, have a good one!

**Comment by dylanjha** [comment]
Hi @simison & @OmgImAlexis thanks for the effort you put in to agenda, having used it in the past and diving into the internals I appreciate the work it takes to maintain an open source project.

In my own use, I was blocked by a couple nagging issues #551 and https://github.com/agenda/agenda/issues/412#issuecomment-331227618. After about 3 months of trying to get some questions answered from the other maintainers, setting up an example project to replicate the issue and I was still blocked so ultimately I moved on to another tool that has turned out to be much better suited for my use case [bee-queue](https://github.com/bee-queue/bee-queue)

Feel free to remove me from the org as Inactive.

Thank you again 🙏 🥂

**Comment by simison** [comment]
>After about 3 months of trying to get some questions answered 

Yup, sadly we're sometimes inactive for months just because busy life — activity on these type of projects tends to come and go in waves.

Often the answer is just _"we don't know"_. :-) That's where we need the help of the community at large.

Appreciate! cheers

**Comment by dylanjha** [comment]
@simison I understand how that goes in waves... Thanks for the attention, I'll keep an eye on how this project progresses and maybe will come back in the future. Thanks!
