### ISSUE TITLE
Auto reconnect  not working

### ISSUE THREAD

**Issue by jodevsa** [agenda/agenda#708]
```
 MongoDB connection is not recoverable, application restart required 

at Agenda.module.exports [as _findAndLockNextJob]
```

**Comment by nogalavi** [comment]
try to catch error: 
agenda.on(`error`, (err, job) => {
  ...
});

By catching it, the recconect will work

**Comment by jodevsa** [comment]
@nogalavi thanks, isn't auto reconnect part of the features that agenda offers ?

**Comment by nogalavi** [comment]
Yes, It does.

Look at the documentation:

> Recovering lost Mongo connections ("auto_reconnect")
Agenda is configured by default to automatically reconnect indefinitely, emitting an error event when no connection is available on each process tick, allowing you to restore the Mongo instance without having to restart the application.

However, if you are using an existing Mongo client you'll need to configure the reconnectTries and reconnectInterval connection settings manually, otherwise you'll find that Agenda will throw an error with the message "MongoDB connection is not recoverable, application restart required" if the connection cannot be recovered within 30 seconds.


What the documentation _doesnt say_, is that if you don't handle the error by: agenda.on(error, (err, job) => {
...
});

The reconnect doesn't work.

I think they should absolutely include that part in the documentation.
Let me know if that works for you.

**Comment by Dartv** [comment]
`agenda.on(error, (err, job) => { ... });` doesn't catch this error: `MongoDB connection is not recoverable, application restart required` and app crashes. Any suggestions?
