### ISSUE TITLE
A month is 30 days and a year is 365 days ... really???

### ISSUE THREAD

**Issue by imkane** [agenda/agenda#757]
Man we keep finding some terrible programming decisions in this package.

You're using https://github.com/agenda/human-interval which hardcodes a month as 30 days (silly) and a year as 365 (silly every 4th year).

Why on earth would you decide to do that? It blows my mind. Just ridiculous.

**Comment by dandv** [comment]
How are you trying to use `human-interval`?

What should `one month` resolve to in this example?

```js
setTimeout(() => {
  // Do something one month from now
}, humanInterval('one month'));
```

**Comment by bhagatd800** [comment]
@dandv We are trying to accomplish how google calendar does it, suppose if a schedule was created for every 3 month starting from march 1st it would run on march 1st, june 1st, spet 1st, dec 1st and so on but suppose if it was schedule to run on 31st of each month starting in jan, since all month do not 31 days  it would skip those month which do not have 31st day so it should run only on jan 31st, march 31, may 31st  so on, we have updated the code as per our need in our fork to accomplish it.

**Comment by wingsbob** [comment]
@bhagatd800 If you've got more complex schedule at requirements, rather than using agenda's interval calculation, you can simply add a `repeatAt` call on the job at the end of your job definition, which allows you to specify the time you'd like to run at next without any constraints. If you want to use this, you need to not set any `repeatInterval`, by using `.every` or similar though

**Comment by bhagatd800** [comment]
@wingsbob as far as i know repeatAt do not provide option of timezone right?

**Comment by wingsbob** [comment]
Nope, because we'll just use the unix timestamp, so if you want to use `repeatAt` to say "tomorrow at 9am" then you'll need to calculate that, construct a date with that timestamp, and pass that to `repeatAt`

**Comment by bhagatd800** [comment]
Ok, thanks.

**Comment by masterbater** [comment]
Can you help me adjust this code with regard to DST in New York
I created the job like this
  job
        .schedule("today at " + utcTime)
        .repeatAt("tomorrow at " + utcTime)
        .save();
the problem is the time is absolute and I want to trigger it that respects DST. How can adjust the nextRunAt?
agenda.define("remindeNoticer", (job, done) => {
  const attrs = job.attrs;
  const data = job.attrs.data;
  checkNotificationMode(data);
  done();
});
