### ISSUE TITLE
Different DB engine?

### ISSUE THREAD

**Issue by reardenlife** [agenda/agenda#788]
I am developing a DApp ( more info at https://stackoverflow.com/questions/55188223/background-task-scheduler-implementation-at-single-page-app  ) and looking for a job scheduler and, apparently, agenda will do the job, but...

Agenda uses non-SQL database, MongoDB while I am using SQL database at my DApp (probably will stick with sqlite3).  It seems inappropriate to use two database engines in one app.  So I wonder what should I do - write my own job scheduler from scratch that uses SQL database or ... ? Any suggestions?

**Comment by dandv** [comment]
I chose Agenda after [extensive research](https://stackoverflow.com/questions/11703010/background-tasks-in-meteor/21351966#21351966) precisely because it's the only job scheduler that supports MongoDB.

> It seems inappropriate to use two database engines in one app.

The vast majority of job queuing packages use Redis, while the apps use Mongo or Postgress or some other database.

Anyway, building support for a RDBS is really out of scope for Agenda, and given the backlog of issues and stalled development we've been having for over a year, chances for that to be implemented are extremely slim.

I would advise building your own scheduling package, if none from my list above satisfy your needs.
