### ISSUE TITLE
New feature request - Consider TimeZone

### ISSUE THREAD

**Issue by sureshballa** [agenda/agenda#79]
First of all I would like to thank for creating such a beautiful flawless scheduling functionality. 
I would like to see new functionality for running scheduler based on different timezone for each job. For example, one job should run as per EST timezone and other one should be based on PST timezone. This way, I will be expose this module as HTTP service and deploy any where across the world and still make usable for any timezone users.

Since cron module, a module agenda internally uses, supports timezone, in the computeNextRunAt function of job.js should pass timezone information from job request to CronTime constructor. This way, nextRunDate is computed as per target timezone that is mentioned for job.

It would be great if this request is considered or I am equally existed to implement this feature if I can contribute.

Thanks,
Suresh

**Comment by keithrz** [comment]
So now that node-cron accepts a timezone parameter, could repeatEvery be changed to accept a timezone parameter?

**Comment by loris** [comment]
I think it would make sense (and would be simple) to allow setting the timezone of the Agenda instance globally (which you probably wanna set to the timezone of the server defining the jobs).
For instance:
`var agenda = new Agenda({timezone: 'Europe/Paris'});`
Store/default it in the Agenda constructor:
`this._timezone = config.timezone || 'Europe/London';`
And passing the value to the CronTime instantiation:
`var cronTime = new CronTime(interval, this.agenda._timezone);`

**Comment by keithrz** [comment]
I'd prefer setting the timezone for each job.  We have some clients on the East Coast, and some one the West Coast.  Say the West Coast client wants their jobs run at 12 noon, 3pm, 6pm, 5 minutes into each hour:
5 12,3,6 * * *
and the west coast client wants their jobs run at 12 noon, 3pm, 6pm, 9pm:
5 12,3,6,9 * * *

In order to implement this currently, we're using logic similar to what @droppedoncaprica described, which works great except for the shifts to/away from Daylight Saving Time, as @miira aluded to.  
Let's say our server is an AWS box, and local time is always in UTC.  So during DST, our jobs had repeatIntervals (in UTC hours) of:
5 19, 22, 1 * * *
and:
5 16, 19, 22 * * *

so once DST ended, we had to change the jobs to:
5 20, 23, 2 * * *
and:
5 17, 20, 23 * * *

and we also needed to set "nextRunAt", unless we modified the repeatInterval before the last job before the time shift.

If we could set the timezone of each job, say, "America/Los_Angeles" for the first and "America/New_York" for the 2nd, then the repeatIntervals could be "5 12, 15, 18 * * *" and "5 12, 15, 18, 21 * * *", and we'd never have to update them for DST time shifts.

**Comment by joegluntz** [comment]
+1 for this overall feature and for timezones specific to each job.

I've found it's very common in integration use cases to need to schedule tasks around an external entity's natural schedule and time zone. It's best for human readability of the schedule, and for nailing the timing around the "daylight savings time" shifts, to define the job's schedule in the local timezone.

A global default timezone for Agenda would be useful too, as long as you could override this per job.

**Comment by simison** [comment]
Seems like this can be closed, see https://github.com/agenda/agenda/pull/267
