### ISSUE TITLE
TypeError: db is not a function

### ISSUE THREAD

**Issue by thardy** [agenda/agenda#868]
I am trying everything to use an existing mongo connection with agenda, and I can't get anything to work.  Here is what I've tried (including solutions from other, similar issues I've read about)...

MongoDb is version 3.3.2 in all attempts.  
config.mongoDbUrl is 'mongodb://localhost:27017/my-db'

first try...
const mongoDb = require('mongodb');
client = await mongoDb.MongoClient.connect(config.mongoDbUrl,{useNewUrlParser:true});
db = client.db();
const agenda = new Agenda({mongo: db()});

result: TypeError: db is not a function

second try...
change the following line...
const agenda = new Agenda({mongo: client.db});

result: TypeError: this._mdb.collection is not a function

third try...
change following line...
const agenda = new Agenda({mongo: client.db('my-db')});

result:
Wait, what?!?  No error.

Ok, so breaking this down helped me solve the problem, but let me change my question to - why does a MongoClient with this connection string...
'mongodb://localhost:27017/my-db' 
still need to use... 
client.db('my-db')
?

**Comment by alanhr** [comment]
Hello @thardy ,

Maybe this is your mistake 
```
db = client.db();
const agenda = new Agenda({mongo: db()});
```
you call db function when you assaine the value in **db** variabel.

try to do this 

```
const db = client.db;
const agenda = new Agenda({mongo: db()});

// OR

const agenda = new Agenda({mongo: client.db())}


```

**Comment by sampathBlam** [comment]
@thardy : As @alanhr pointed out, I would recommend you to try passing in `client.db()` without the name of the database. (As you had already set the db name in the connection string for MongoClient). 

As per the official documentation, we can `Use an existing mongodb-native MongoClient/Db instance` for the `mongo `param during agenda initialization. 
Hence it would even be enough if you just pass the MongoClient instance, which was connected using the full db url, instead of passing the db instance by calling client.db().

**Comment by leonardlin** [comment]
this has been fixed https://github.com/agenda/agenda/pull/1178

**Comment by db079** [comment]
This is happen if you are doing like this
```
const { MongoClient } = require("mongodb");
const uri = "mongodb://loclahost:27017/";
const client = new MongoClient(uri);
```
just replace **localhost** with **127.0.0.1**
```
const { MongoClient } = require("mongodb");
const uri = "mongodb://127.0.0.1:27017/";
const client = new MongoClient(uri);
```
